@Boonkrua_HostAddress = http://localhost:5214
@id = variable value

GET {{Boonkrua_HostAddress}}/topic/{{id}}}/
Accept: application/json

GET {{Boonkrua_HostAddress}}/topic
Accept: application/json

###
